
services:
  # Servicio para el backend (Node.js)
  backend:
    image: zerojose/universidad-backend:v1.1
    container_name: backend-universidad
    restart: always
    ports:
      - "3000:3000"
    networks:
      - consultorio_network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=consultorio-universidad
      - DB_USER=postgres
      - DB_PASSWORD=D3v310p34DF
    depends_on:
      - db

  db:
    image: postgres:16.6-alpine3.21
    container_name: universidad-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D3v310p34DF
      POSTGRES_DB: consultorio-universidad
    ports:
      - "5432:5432"
    networks:
      - consultorio_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Servicio para el frontend (React, Angular, etc.)
  frontend:
    image: zerojose/universidad-frontennd:v1.1
    container_name: frontend-universidad
    restart: always
    ports:
      - "8383:8080"
    networks:
      - consultorio_network
    depends_on:
      - backend

networks:
  consultorio_network:
    driver: bridge

volumes:
  pgdata: